#!/bin/bash

# Edit this script with your script names for openocd

INTERFACE=/usr/share/openocd/scripts/interface/stlink-v2.cfg
TARGET=openocd_target_script/stm32f1x.cfg
LOG=~/openocd_stdout.log

echo "Target script: $TARGET"
echo "Interface script: $INTERFACE"
echo "Starting OpenOCD and GDB server on localhost:3333"
echo "process is in background"
openocd -f $INTERFACE -f $TARGET 1>$LOG # 2>/dev/null & 
sleep 1
ps

